# Generated by Django 5.1.7 on 2025-10-20 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='statements/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('statement_period_start', models.DateField(blank=True, null=True)),
                ('statement_period_end', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('statement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analyzer.bankstatement')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('category', models.CharField(choices=[('INCOME', 'Income'), ('FOOD', 'Food & Dining'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills & Utilities'), ('TRANSPORT', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('LOAN', 'Loan & EMI'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.bankstatement')),
            ],
        ),
    ]
