# Generated by Django 5.1.7 on 2025-12-05 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('INCOME', 'Income'), ('FOOD', 'Food & Dining'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills & Utilities'), ('TRANSPORT', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTHCARE', 'Healthcare'), ('LOAN', 'Loan & EMI'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('AND', 'All conditions must match (AND)'), ('OR', 'Any condition matches (OR)')], default='AND', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('KEYWORD', 'Keyword in Description'), ('AMOUNT', 'Amount Range'), ('DATE', 'Date Range'), ('SOURCE', 'Transaction Source/Channel')], max_length=20)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('keyword_match_type', models.CharField(blank=True, choices=[('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts With'), ('ENDS_WITH', 'Ends With'), ('EXACT', 'Exact Match')], max_length=20)),
                ('amount_operator', models.CharField(blank=True, choices=[('EQUALS', 'Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('BETWEEN', 'Between'), ('GREATER_THAN_EQUAL', 'Greater Than or Equal'), ('LESS_THAN_EQUAL', 'Less Than or Equal')], max_length=20)),
                ('amount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_value2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('source_channel', models.CharField(blank=True, choices=[('PAYTM', 'Paytm'), ('PHONEPE', 'PhonePe'), ('GOOGLE_PAY', 'Google Pay'), ('UPI', 'UPI'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('NET_BANKING', 'Net Banking'), ('CHEQUE', 'Cheque'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS')], max_length=50)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='analyzer.rule')),
            ],
        ),
    ]
