# Generated by Django 5.1.7 on 2025-12-05 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rule_rulecondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='file_type',
            field=models.CharField(choices=[('PDF', 'PDF Document'), ('EXCEL', 'Excel Spreadsheet'), ('CSV', 'CSV File')], default='PDF', max_length=10),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='statement_file',
            field=models.FileField(blank=True, null=True, upload_to='statements/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
