# Generated by Django 5.1.7 on 2025-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_remove_bankstatement_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
