# Generated by Django 5.1.7 on 2025-12-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_bankaccount_account_type_bankaccount_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='rules_applied',
            field=models.BooleanField(default=False),
        ),
    ]
