# Generated by Django 5.1.7 on 2025-12-12 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_bankstatement_rules_applied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#95a5a6', max_length=7)),
                ('icon', models.CharField(default='fa-circle', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Custom Categories',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('AND', 'All conditions must match (AND)'), ('OR', 'Any condition matches (OR)')], default='AND', max_length=3)),
                ('custom_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='analyzer.customcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_category_rules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomCategoryRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('KEYWORD', 'Keyword in Description'), ('AMOUNT', 'Amount Range'), ('DATE', 'Date Range')], max_length=20)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('keyword_match_type', models.CharField(blank=True, choices=[('CONTAINS', 'Contains'), ('STARTS_WITH', 'Starts With'), ('ENDS_WITH', 'Ends With'), ('EXACT', 'Exact Match')], max_length=20)),
                ('amount_operator', models.CharField(blank=True, choices=[('EQUALS', 'Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('BETWEEN', 'Between'), ('GREATER_THAN_EQUAL', 'Greater Than or Equal'), ('LESS_THAN_EQUAL', 'Less Than or Equal')], max_length=20)),
                ('amount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_value2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='analyzer.customcategoryrule')),
            ],
        ),
    ]
